blank_issues_enabled: true
contact_links:
  - name: "📜 Règlement des Boards"
    url: "https://reptile-new.github.io/guild-leaderbord/reglement.html"
    about: "Vérification des records, barèmes de points, formats de tournoi."
